### ISSUE TITLE
Railway techs

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pyindustry#14]
Railway stage 1 and 2 do not depend on vanilla railways. They also do not depend on Niobium or Nexelit which are both required to construct them.

Tested with only CP, FE, Industry

[Originally reported in pycoalprocessing](https://github.com/pyanodon/pycoalprocessing/issues/93#issue-947288900)

**Comment by Havvy** [comment]
With just CP and Industry, Railway 1 technology doesn't unlock anything at all.

**Comment by ShadowGlass0** [comment]
@kingarthur91 Railway 1 is in red science, but the jerry cans needed to fuel them are in plastic tech at green science.

1. We could move plastic to red science. Both aromatics and syngas are available
2. Or change railway back to green science
3. Or add some early crappy non-plastic based fuel option

**Comment by kingarthur91** [comment]
that a pycp issue and the plan was to be able to burn normal solid items as well like coal before canned fluids are available.

**Comment by ShadowGlass0** [comment]
This is fine In PyCp only. The vanilla railway tech is green science, and we made it require plastics, so it can use the jerry cans. PyInd moves the railway to red science. Should I just add back the chemical fuel category to the vanilla loco?

**Comment by kingarthur91** [comment]
Already did
