### ISSUE TITLE
Coal Processing 2 + py Industry

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pyindustry#17]
Mods: CP, FE, Industry

Coal Processing 2 adds Niobium pipes and Nexelit accumulators, however it does not depend on Niobium, and Chemical Science Pack technologies which unlock both of those.

[From pycoalprocessing](https://github.com/pyanodon/pycoalprocessing/issues/104#issue-947323887)

**Comment by ShadowGlass0** [comment]
I think PyIndustry issues should be fixed in PyIndustry without messing with the other mods. Just add the industry recipes to the correct tech, depending on what other mods are active.

**Comment by ShadowGlass0** [comment]
About the accumulators: We have the vanilla accumulators at green science, so I'm moving the nexelit accu to chemical science. I'm thinking electric energy distribution 2 would be a good fit, unless Py wants to make a new tech icon for a separate tech.
@kingarthur91 Thoughts?

**Comment by kingarthur91** [comment]
ya i think moving them to a separate tech will work and if your going to add c2 to the nexelit accumulator i would add c1 to the vanilla version.
