### ISSUE TITLE
Construction robotics + engine

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pyindustry#31]
Construction robotics is red science tech, and it requires engine, which is green science.

We could move the vanilla engine tech to red science, or remove the engine ingredient from the py construction bot & py roboport.

**Comment by kingarthur91** [comment]
Is there anything stopping the engine from being a red tech?

**Comment by ShadowGlass0** [comment]
Nope, it's jus steel & iron

**Comment by ShadowGlass0** [comment]
Actually, engine unit needs 3 ingredients and can't be handcrafted. Basic assembling machine can only do 2 ingredients. So based on that it needs to be green tech.

**Comment by ShadowGlass0** [comment]
We could just remove the engine from the construction robot...

**Comment by kingarthur91** [comment]
ya we can add it back in the later mods or something. its already a red tech with the full set.
