### ISSUE TITLE
Can't use fuel canisters with advanced locomotive

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pyindustry#45]
I can use fuel canisters with the first locomotive, but not with the advanced locomotive. If this is intended than the advanced locomotive might not be worth using, and instead jump from first locomotive to high tech floating locomotive directly.

<img width="811" alt="image" src="https://user-images.githubusercontent.com/22458042/150560469-79e6cb28-2e74-43d4-958c-047d7566ec6a.png">

<img width="380" alt="image" src="https://user-images.githubusercontent.com/22458042/150560521-bf046dbc-c4db-4b5c-826b-d23f3465e08d.png">

**Comment by oorzkws** [comment]
This is resolved in dev, canisters as fuel are now exclusive to the higher tier locomotives.
