### ISSUE TITLE
migration error - assignID niobium-plate does not exist

### ISSUE THREAD

**Issue by filipagh** [pyanodon/pyindustry#88]
after comment out game print on this error [#194 ](https://github.com/pyanodon/pyalienlife/issues/194)

i have this broken recipe

![image](https://user-images.githubusercontent.com/22474494/211051587-16cc9525-d07b-4da4-ae54-29023805afef.png)

**Comment by kingarthur91** [comment]
It's already been fixed but you need base version 1.1.74 due to some other bug fixes that required things added in that version

**Comment by filipagh** [comment]
hello @kingarthur91 im on 1.1.74

**Comment by notnotmelon** [comment]
In this screenshot, it shows you are using pY industry version 2.0.4
Update to version 2.0.5

**Comment by filipagh** [comment]
thanks  v2.0.5 fixed it
